### ISSUE TITLE
Fechas de incorporaciones

### ISSUE THREAD

**Issue by toblich** [AndresOtero/ModelosYOptimizacionI#1]
Viendo el commit 1b028f86108880eaf7bcd96bafd472ef97dca701, hay un tema en `incorporaciones{f in FECHAS, i in JUGADORES}`.

### Problema

Viendo que en las restricciones usan siempre `incorporaciones[f+1, i]`, deduzco que si un jugador está en la fecha f+1 y no en la f, consideran que es una incorporación de la fecha f+1. Por lo tanto, las fechas en las que puede haber incorporaciones son **todas menos la primera**. Sin embargo, en la definición de la variable admiten **todas incluyendo la primera**. 

Luego, con las restricciones, dejan libres las incorporaciones de la fecha 1. En consecuencia, van a llegar al mismo puntaje final pero pueden tener dos problemas:

- El valor que tomen las variables `incorporaciones[1, i], para todo i` no tiene sentido.
- Por el punto anterior, hay muchísimas soluciones alternativas. Debido al algoritmo de resolución (Branch & Bound, o bien Branch & Cut al usar cortes - los verán en la teórica después del parcial), esto podría demorar muchísimo la resolución.

### Solución

Alcanza con redefinir el conjunto `FECHAS_HABILITADAS_TRANSFERENCIAS` para que vaya de 2 a 15 en vez de ir de 1 a 14. Luego, la variable `incorporaciones` toma valor sobre este nuevo conjunto (y los jugadores, claro) en lugar de todas las fechas. Fíjense después de ajustar las restricciones de incorporaciones para que también sean sobre este conjunto, posiblemente corriendo en una unidad los subíndices respecto a como los tienen ahora.

**Comment by AndresOtero** [comment]
Problema Solucionado
